#!/bin/bash

killall GitX

HUB_USER=343max
REPO=stack_demo_repo

hub delete -y $HUB_USER/$REPO

DIR=/tmp/$REPO
rm -rf $DIR
mkdir -p $DIR
cd $DIR

show_gitx() {
    gitx
    read -p "Press enter to continue"
    killall GitX
    echo "done"
}

git init

echo "This is a autogenerated demo repo and shouldn't be used for anything" > README.md
git add .
git commit -m "Initial Commit"

echo "Except for having debugging & demoing!" >> README.md
git add .
git commit -m "Clarified Readme"

hub create -p
git push -u origin master

git co -b feature
echo "
struct Greating {
    let name: String
}
" > hello.swift
git add .
git commit -m "created Greating struct"

echo "
struct Greating {
    let name: String

    func sayHello() { print(\"Hello \" + self.name) }
}
" > hello.swift

git add .
git commit -m "added sayHello func"

echo "
struct Greating {
    let name: String

    func sayHello() { print(\"Hello \" + self.name) }
}

Greating(\"world\").sayHello()
" > hello.swift

git add .
git commit -m "calling sayHello"

# show_gitx



# echo "
# struct Greeting {
#     let name: String

#     func sayHello() { print(\"Hello \" + self.name) }
# }

# Greeting(\"world\").sayHello()
# " > hello.swift
# git add .

# show_gitx

# git absorb
# git rebase -i --autosquash master

# show_gitx
